# Auth and OTP config
app.auth.jwt-secret=${APP_JWT_SECRET:${JWT_SECRET_KEY}}
app.auth.jwt-expiration-minutes=${APP_JWT_EXP_MINUTES}
app.auth.otp-expiration-minutes=${APP_OTP_EXP_MINUTES}
app.auth.otp-resend-cooldown-seconds=${APP_OTP_RESEND_SECONDS}
app.auth.forgot-password-token-expiration-minutes=${APP_FORGOT_PASSWORD_TOKEN_EXP_MINUTES}
app.auth.forgot-password-max-attempts=${APP_FORGOT_PASSWORD_MAX_ATTEMPTS}
app.auth.mail-from=${APP_MAIL_FROM}
app.auth.refresh-token-expiration-days=${APP_REFRESH_TOKEN_EXP_DAYS}
app.auth.refresh-token-cookie-name=${APP_REFRESH_TOKEN_COOKIE_NAME}
app.auth.refresh-token-cookie-secure=${APP_REFRESH_TOKEN_COOKIE_SECURE}
app.auth.refresh-token-cookie-same-site=${APP_REFRESH_TOKEN_COOKIE_SAMESITE}
app.auth.refresh-token-cookie-path=${APP_REFRESH_TOKEN_COOKIE_PATH}


# Mail server config (set by env vars for real SMTP)
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS}