spring.application.name=sport_pro_be
spring.config.import=optional:classpath:config/auth.properties,optional:classpath:config/database.properties,optional:classpath:config/common.properties

spring.cache.type=none


